data_generation:
  bronze_layer_path: bronze_layer/
  silver_layer_path: silver_layer/
  users_count: 10000
  items_count: 10000
  transactions_count: 18000
  noise_level: 0.03
  null_wrong_proportion: 0.5
  save_locally: false
  save_to_cloud: true
  save_to_bq: true
  load_from_cloud: true

queries:
  queries_path: sql_queries/
  query_files: ['day_to_day_sales.sql', 'top_spenders.sql', 'performance_analysis_by_country.sql', 'sales_moving_average.sql', 'top_products_by_category.sql']

database:
  gold_layer_tables_schema: gold_layer/create_tables.sql
  required_tables:
    creation_order: ['users', 'products', 'transactions']
    drop_order: ['transactions', 'products', 'users']

dag:
  retries: 2
  retries_delay: 60

cloud:
  default_location: US
  gcs_bucket_name: big-data-project-bucket-123456
  bq_gold_layer_dataset: gold_layer
