data_generation:
  data_path: data/
  users_count: 2000
  items_count: 1000
  transactions_count: 12000

queries:
  queries_path: sql_queries/
  query_files: ['day_to_day_sales.sql', 'top_spenders.sql', 'performance_analysis_by_country.sql', 'sales_moving_average.sql', 'top_products_by_category.sql']

database:
  scripts_path: database_creation/
  setup_script: database_creation/create_tables.sql
  required_tables: ['users', 'products', 'transactions']